/**
 * Occupation-specific specialty preset suggestions.
 * Used in SpecialtyTagInput for quick selection.
 * Search/filter uses only occupation_services (official service types), NOT specialties.
 */

export const SPECIALTY_PRESETS_BY_OCCUPATION: Record<string, string[]> = {
  cleaner: [
    'Pet hair removal',
    'Eco-friendly cleaning',
    'Move-out cleaning',
    'Airbnb turnover',
    'Stain treatment',
    'Office cleaning',
    'Post-construction cleanup',
    'Same-day service',
  ],
  handyman: [
    'TV mounting',
    'Furniture assembly',
    'Drywall patching',
    'Door repair',
    'Shelving install',
    'Smart home install',
    'Deck repair',
    'Minor plumbing (non-licensed)',
  ],
  'home-organizer': [
    'Closets',
    'Garages',
    'Home offices',
    'Downsizing',
    'KonMari method',
    'Hoarder support',
    'Moving prep',
  ],
  painter: [
    'Interior',
    'Exterior',
    'Cabinet refinishing',
    'Commercial',
    'Epoxy flooring',
    'Decorative finishes',
  ],
  landscaper: [
    'Lawn care',
    'Garden design',
    'Tree pruning',
    'Mulching',
    'Edging',
    'Seasonal cleanup',
  ],
  'snow-removal': [
    'Residential driveways',
    'Commercial lots',
    'Walkways',
    'Roof clearing',
    'Ice management',
  ],
  tutor: [
    'Algebra',
    'SAT prep',
    'Homework help',
    'Reading support',
    'Test prep',
    'AP courses',
    'ESL',
    'STEM',
  ],
  'personal-trainer': [
    'Strength training',
    'Weight loss',
    'Senior fitness',
    'Pre/postnatal',
    'Rehabilitation',
    'Athletic performance',
  ],
  photographer: [
    'Weddings',
    'Portraits',
    'Real estate',
    'Headshots',
    'Events',
    'Product photography',
    'Newborn',
  ],
  videographer: [
    'Weddings',
    'Corporate',
    'Music videos',
    'Real estate',
    'Social media',
    'Documentary',
  ],
  dj: [
    'Weddings',
    'Corporate events',
    'Private parties',
    'Karaoke',
    'Latin music',
    'Hip-hop/R&B',
  ],
  'event-planner': [
    'Weddings',
    'Corporate',
    'Birthday parties',
    'Baby showers',
    'Fundraisers',
    'Private dinners',
  ],
  chef: [
    'Private dinners',
    'Meal prep',
    'Catering',
    'Italian cuisine',
    'BBQ',
    'Dietary restrictions',
  ],
  'makeup-artist': [
    'Bridal',
    'Editorial',
    'Special effects',
    'Skincare',
    'Airbrush',
    'Film/TV',
  ],
  'dog-walker': [
    'Puppies',
    'Senior dogs',
    'Multiple dogs',
    'Reactive dogs',
    'Long walks',
    'Medication admin',
  ],
  barber: [
    'Fades',
    'Beards',
    'Kids cuts',
    'Classic cuts',
    'Hot towel shave',
  ],
  mechanic: [
    'Brakes',
    'Engine repair',
    'Transmission',
    'Diagnostics',
    'Imports',
    'Vintage cars',
  ],
  'car-detailer': [
    'Interior deep clean',
    'Paint correction',
    'Ceramic coating',
    'Mobile service',
    'Fleet detailing',
  ],
  mover: [
    'Small Apartment Moves',
    'Heavy Lifting',
    'Packing Help',
    'Last-Minute Moves',
    'Pianos',
    'Storage',
  ],
  'it-technician': [
    'Network setup',
    'Computer repair',
    'Data recovery',
    'Smart home',
    'Business IT',
  ],
};

/** Get presets for an occupation slug. Returns empty array if none. */
export function getSpecialtyPresets(occupationSlug: string): string[] {
  return SPECIALTY_PRESETS_BY_OCCUPATION[occupationSlug] ?? [];
}
